In [ ]:
import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.layers import Input, Bidirectional, Dense, Conv1D, LSTM, Flatten, Concatenate, Attention, GlobalAveragePooling1D
from utilz import *
from tensorflow.keras.callbacks import ModelCheckpoint
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

# load data

In [2]:
w2v_embs = load_features('./data/textual_wav2vec.pkl')
bert_embs = load_features('./data/textual_bert.pkl')
label = load_features('./data/labels.pkl')

# Model 1

In [3]:
x = Input((36,100))
h = LSTM(64, return_sequences=False, return_state=False)(x)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 36, 100)]         0         
                                                                 
 lstm (LSTM)                 (None, 64)                42240     
                                                                 
 dense (Dense)               (None, 3)                 195       
                                                                 
Total params: 42,435
Trainable params: 42,435
Non-trainable params: 0
_________________________________________________________________


2022-10-04 09:54:45.862630: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-04 09:54:45.928393: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-04 09:54:45.928504: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-04 09:54:45.928922: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compi

In [7]:
callback_list = [ModelCheckpoint(filepath='./res/T_model_LSTM_wav2vec.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(w2v_embs['train']), y=np.asarray(label['train']), batch_size=16, epochs=15, 
            validation_data=[np.asarray(w2v_embs['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/15
85/86 [============================>.] - ETA: 0s - loss: 0.9986 - acc: 0.5397

INFO:tensorflow:Assets written to: ./res/T_model_LSTM_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_LSTM_wav2vec.tf/assets


86/86 [==============================] - 4s 34ms/step - loss: 0.9986 - acc: 0.5395 - val_loss: 0.9868 - val_acc: 0.5439
Epoch 2/15
86/86 [==============================] - 1s 10ms/step - loss: 0.9838 - acc: 0.5424 - val_loss: 0.9781 - val_acc: 0.5439
Epoch 3/15
86/86 [==============================] - ETA: 0s - loss: 0.9792 - acc: 0.5439

INFO:tensorflow:Assets written to: ./res/T_model_LSTM_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_LSTM_wav2vec.tf/assets


86/86 [==============================] - 3s 29ms/step - loss: 0.9792 - acc: 0.5439 - val_loss: 0.9719 - val_acc: 0.5461
Epoch 4/15
84/86 [============================>.] - ETA: 0s - loss: 0.9730 - acc: 0.5417

INFO:tensorflow:Assets written to: ./res/T_model_LSTM_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_LSTM_wav2vec.tf/assets


86/86 [==============================] - 3s 32ms/step - loss: 0.9738 - acc: 0.5417 - val_loss: 0.9739 - val_acc: 0.5504
Epoch 5/15
81/86 [===========================>..] - ETA: 0s - loss: 0.9718 - acc: 0.5448

INFO:tensorflow:Assets written to: ./res/T_model_LSTM_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_LSTM_wav2vec.tf/assets


86/86 [==============================] - 2s 29ms/step - loss: 0.9682 - acc: 0.5475 - val_loss: 0.9753 - val_acc: 0.5526
Epoch 6/15
86/86 [==============================] - 1s 10ms/step - loss: 0.9609 - acc: 0.5402 - val_loss: 0.9766 - val_acc: 0.5504
Epoch 7/15
82/86 [===========================>..] - ETA: 0s - loss: 0.9669 - acc: 0.5396

INFO:tensorflow:Assets written to: ./res/T_model_LSTM_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_LSTM_wav2vec.tf/assets


86/86 [==============================] - 3s 32ms/step - loss: 0.9654 - acc: 0.5402 - val_loss: 0.9718 - val_acc: 0.5570
Epoch 8/15
86/86 [==============================] - 1s 10ms/step - loss: 0.9595 - acc: 0.5453 - val_loss: 0.9739 - val_acc: 0.5395
Epoch 9/15
86/86 [==============================] - 1s 10ms/step - loss: 0.9558 - acc: 0.5490 - val_loss: 0.9723 - val_acc: 0.5351
Epoch 10/15
86/86 [==============================] - 1s 10ms/step - loss: 0.9575 - acc: 0.5519 - val_loss: 0.9750 - val_acc: 0.5329
Epoch 11/15
86/86 [==============================] - 1s 10ms/step - loss: 0.9607 - acc: 0.5431 - val_loss: 0.9711 - val_acc: 0.5504
Epoch 12/15
86/86 [==============================] - 1s 10ms/step - loss: 0.9513 - acc: 0.5468 - val_loss: 0.9741 - val_acc: 0.5263
Epoch 13/15
86/86 [==============================] - 1s 10ms/step - loss: 0.9603 - acc: 0.5541 - val_loss: 0.9725 - val_acc: 0.5504
Epoch 14/15
86/86 [==============================] - 1s 10ms/step - loss: 0.9571 - acc: 0.

In [73]:
model = tf.keras.models.load_model('./res/T_model_LSTM_wav2vec.tf')
pred = model.predict(np.asarray(w2v_embs['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 4ms/step
              precision    recall  f1-score   support

         Neg     0.5550    0.9758    0.7076       248
         Pos     0.3333    0.0429    0.0759       140
         Neu     0.3333    0.0145    0.0278        69

    accuracy                         0.5449       457
   macro avg     0.4072    0.3444    0.2704       457
weighted avg     0.4536    0.5449    0.4115       457

[[242   5   1]
 [133   6   1]
 [ 61   7   1]]


In [11]:
x = Input((36,768))
h = LSTM(64, return_sequences=False, return_state=False)(x)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 36, 768)]         0         
                                                                 
 lstm_3 (LSTM)               (None, 64)                213248    
                                                                 
 dense_3 (Dense)             (None, 3)                 195       
                                                                 
Total params: 213,443
Trainable params: 213,443
Non-trainable params: 0
_________________________________________________________________


In [12]:
callback_list = [ModelCheckpoint(filepath='./res/T_model_LSTM_bert.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(bert_embs['train']), y=np.asarray(label['train']), batch_size=16, epochs=15, 
            validation_data=[np.asarray(bert_embs['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/15


2022-09-24 16:38:49.964075: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 151289856 exceeds 10% of free system memory.


86/86 [==============================] - ETA: 0s - loss: 0.9963 - acc: 0.5373

2022-09-24 16:38:51.881161: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 50429952 exceeds 10% of free system memory.


INFO:tensorflow:Assets written to: ./res/T_model_LSTM_bert.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_LSTM_bert.tf/assets


86/86 [==============================] - 4s 35ms/step - loss: 0.9963 - acc: 0.5373 - val_loss: 0.9586 - val_acc: 0.5329
Epoch 2/15
86/86 [==============================] - ETA: 0s - loss: 0.8845 - acc: 0.6023

INFO:tensorflow:Assets written to: ./res/T_model_LSTM_bert.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_LSTM_bert.tf/assets


86/86 [==============================] - 3s 35ms/step - loss: 0.8845 - acc: 0.6023 - val_loss: 0.9385 - val_acc: 0.5877
Epoch 3/15
86/86 [==============================] - 1s 13ms/step - loss: 0.7409 - acc: 0.6915 - val_loss: 0.9534 - val_acc: 0.5789
Epoch 4/15
86/86 [==============================] - 1s 13ms/step - loss: 0.5823 - acc: 0.7939 - val_loss: 1.0869 - val_acc: 0.5746
Epoch 5/15
86/86 [==============================] - 1s 13ms/step - loss: 0.4292 - acc: 0.8545 - val_loss: 1.3210 - val_acc: 0.5614
Epoch 6/15
86/86 [==============================] - 1s 13ms/step - loss: 0.3392 - acc: 0.8904 - val_loss: 1.1649 - val_acc: 0.5658
Epoch 7/15
86/86 [==============================] - 1s 13ms/step - loss: 0.2814 - acc: 0.9189 - val_loss: 1.4105 - val_acc: 0.5263
Epoch 8/15
86/86 [==============================] - 1s 13ms/step - loss: 0.2197 - acc: 0.9415 - val_loss: 1.7003 - val_acc: 0.5395
Epoch 9/15
86/86 [==============================] - 1s 13ms/step - loss: 0.1540 - acc: 0.9649 

In [72]:
model = tf.keras.models.load_model('./res/T_model_LSTM_bert.tf')
pred = model.predict(np.asarray(bert_embs['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 6ms/step
              precision    recall  f1-score   support

         Neg     0.6347    0.8548    0.7285       248
         Pos     0.5082    0.4429    0.4733       140
         Neu     1.0000    0.0145    0.0286        69

    accuracy                         0.6018       457
   macro avg     0.7143    0.4374    0.4101       457
weighted avg     0.6511    0.6018    0.5446       457

[[212  36   0]
 [ 78  62   0]
 [ 44  24   1]]


# Model 2

In [15]:
x = Input((36,100))
h = Bidirectional(LSTM(64, return_sequences=False, return_state=False))(x)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 36, 100)]         0         
                                                                 
 bidirectional (Bidirectiona  (None, 128)              84480     
 l)                                                              
                                                                 
 dense_4 (Dense)             (None, 3)                 387       
                                                                 
Total params: 84,867
Trainable params: 84,867
Non-trainable params: 0
_________________________________________________________________


In [16]:
callback_list = [ModelCheckpoint(filepath='./res/T_model_BLSTM_wav2vec.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(w2v_embs['train']), y=np.asarray(label['train']), batch_size=16, epochs=15, 
            validation_data=[np.asarray(w2v_embs['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/15
83/86 [===========================>..] - ETA: 0s - loss: 0.9877 - acc: 0.5377

INFO:tensorflow:Assets written to: ./res/T_model_BLSTM_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_BLSTM_wav2vec.tf/assets


86/86 [==============================] - 8s 77ms/step - loss: 0.9901 - acc: 0.5373 - val_loss: 0.9854 - val_acc: 0.5439
Epoch 2/15
86/86 [==============================] - 1s 11ms/step - loss: 0.9702 - acc: 0.5417 - val_loss: 0.9729 - val_acc: 0.5439
Epoch 3/15
86/86 [==============================] - 1s 11ms/step - loss: 0.9650 - acc: 0.5439 - val_loss: 0.9768 - val_acc: 0.5417
Epoch 4/15
86/86 [==============================] - 1s 11ms/step - loss: 0.9585 - acc: 0.5439 - val_loss: 0.9734 - val_acc: 0.5395
Epoch 5/15
85/86 [============================>.] - ETA: 0s - loss: 0.9554 - acc: 0.5515

INFO:tensorflow:Assets written to: ./res/T_model_BLSTM_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_BLSTM_wav2vec.tf/assets


86/86 [==============================] - 6s 74ms/step - loss: 0.9558 - acc: 0.5512 - val_loss: 0.9738 - val_acc: 0.5526
Epoch 6/15
86/86 [==============================] - 1s 11ms/step - loss: 0.9543 - acc: 0.5417 - val_loss: 0.9796 - val_acc: 0.5461
Epoch 7/15
86/86 [==============================] - 1s 11ms/step - loss: 0.9577 - acc: 0.5556 - val_loss: 0.9818 - val_acc: 0.5439
Epoch 8/15
86/86 [==============================] - 1s 11ms/step - loss: 0.9488 - acc: 0.5497 - val_loss: 0.9711 - val_acc: 0.5482
Epoch 9/15
86/86 [==============================] - 1s 11ms/step - loss: 0.9428 - acc: 0.5534 - val_loss: 0.9655 - val_acc: 0.5373
Epoch 10/15
86/86 [==============================] - 1s 11ms/step - loss: 0.9473 - acc: 0.5534 - val_loss: 0.9673 - val_acc: 0.5417
Epoch 11/15
86/86 [==============================] - 1s 11ms/step - loss: 0.9447 - acc: 0.5556 - val_loss: 0.9676 - val_acc: 0.5461
Epoch 12/15
86/86 [==============================] - 1s 11ms/step - loss: 0.9392 - acc: 0.56

In [71]:
model = tf.keras.models.load_model('./res/T_model_BLSTM_wav2vec.tf')
pred = model.predict(np.asarray(w2v_embs['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 5ms/step
              precision    recall  f1-score   support

         Neg     0.5510    0.9798    0.7054       248
         Pos     0.4375    0.0500    0.0897       140
         Neu     0.0000    0.0000    0.0000        69

    accuracy                         0.5470       457
   macro avg     0.3295    0.3433    0.2650       457
weighted avg     0.4330    0.5470    0.4103       457

[[243   5   0]
 [133   7   0]
 [ 65   4   0]]


/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

In [18]:
x = Input((36,768))
h = Bidirectional(LSTM(64, return_sequences=False, return_state=False))(x)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 36, 768)]         0         
                                                                 
 bidirectional_1 (Bidirectio  (None, 128)              426496    
 nal)                                                            
                                                                 
 dense_5 (Dense)             (None, 3)                 387       
                                                                 
Total params: 426,883
Trainable params: 426,883
Non-trainable params: 0
_________________________________________________________________


In [19]:
callback_list = [ModelCheckpoint(filepath='./res/T_model_BLSTM_bert.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(bert_embs['train']), y=np.asarray(label['train']), batch_size=16, epochs=15, 
            validation_data=[np.asarray(bert_embs['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/15


2022-09-24 16:43:02.547892: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 151289856 exceeds 10% of free system memory.


85/86 [============================>.] - ETA: 0s - loss: 0.9724 - acc: 0.5331

INFO:tensorflow:Assets written to: ./res/T_model_BLSTM_bert.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_BLSTM_bert.tf/assets


86/86 [==============================] - 9s 85ms/step - loss: 0.9722 - acc: 0.5336 - val_loss: 0.9352 - val_acc: 0.6031
Epoch 2/15
86/86 [==============================] - 1s 15ms/step - loss: 0.7744 - acc: 0.6871 - val_loss: 0.9537 - val_acc: 0.5855
Epoch 3/15
86/86 [==============================] - 1s 15ms/step - loss: 0.5481 - acc: 0.7924 - val_loss: 0.9633 - val_acc: 0.5811
Epoch 4/15
86/86 [==============================] - 1s 15ms/step - loss: 0.3064 - acc: 0.8999 - val_loss: 1.2066 - val_acc: 0.5658
Epoch 5/15
86/86 [==============================] - 1s 15ms/step - loss: 0.1259 - acc: 0.9664 - val_loss: 1.5463 - val_acc: 0.5373
Epoch 6/15
86/86 [==============================] - 1s 15ms/step - loss: 0.0581 - acc: 0.9890 - val_loss: 1.7986 - val_acc: 0.5592
Epoch 7/15
86/86 [==============================] - 1s 15ms/step - loss: 0.0167 - acc: 0.9963 - val_loss: 2.0143 - val_acc: 0.5877
Epoch 8/15
86/86 [==============================] - 1s 15ms/step - loss: 0.0055 - acc: 0.9993 

In [70]:
model = tf.keras.models.load_model('./res/T_model_BLSTM_bert.tf')
pred = model.predict(np.asarray(bert_embs['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 7ms/step
              precision    recall  f1-score   support

         Neg     0.6224    0.8306    0.7116       248
         Pos     0.4918    0.4286    0.4580       140
         Neu     0.2500    0.0145    0.0274        69

    accuracy                         0.5842       457
   macro avg     0.4547    0.4246    0.3990       457
weighted avg     0.5261    0.5842    0.5306       457

[[206  40   2]
 [ 79  60   1]
 [ 46  22   1]]


# Model 3

In [36]:
x = Input((36,100))
h = Attention()([x, x])
h = Bidirectional(LSTM(64, return_sequences=False, return_state=False))(h)

res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_10"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_11 (InputLayer)          [(None, 36, 100)]    0           []                               
                                                                                                  
 attention (Attention)          (None, 36, 100)      0           ['input_11[0][0]',               
                                                                  'input_11[0][0]']               
                                                                                                  
 bidirectional_6 (Bidirectional  (None, 128)         84480       ['attention[0][0]']              
 )                                                                                                
                                                                                           

In [37]:
callback_list = [ModelCheckpoint(filepath='./res/T_model_AttBLSTM_wav2vec.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(w2v_embs['train']), y=np.asarray(label['train']), batch_size=16, epochs=15, 
            validation_data=[np.asarray(w2v_embs['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/15
82/86 [===========================>..] - ETA: 0s - loss: 0.9928 - acc: 0.5320

INFO:tensorflow:Assets written to: ./res/T_model_AttBLSTM_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_AttBLSTM_wav2vec.tf/assets


86/86 [==============================] - 8s 74ms/step - loss: 0.9911 - acc: 0.5329 - val_loss: 0.9851 - val_acc: 0.5439
Epoch 2/15
83/86 [===========================>..] - ETA: 0s - loss: 0.9733 - acc: 0.5392

INFO:tensorflow:Assets written to: ./res/T_model_AttBLSTM_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_AttBLSTM_wav2vec.tf/assets


86/86 [==============================] - 7s 81ms/step - loss: 0.9702 - acc: 0.5395 - val_loss: 0.9743 - val_acc: 0.5504
Epoch 3/15
86/86 [==============================] - 1s 12ms/step - loss: 0.9601 - acc: 0.5490 - val_loss: 0.9743 - val_acc: 0.5461
Epoch 4/15
86/86 [==============================] - ETA: 0s - loss: 0.9584 - acc: 0.5497

INFO:tensorflow:Assets written to: ./res/T_model_AttBLSTM_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_AttBLSTM_wav2vec.tf/assets


86/86 [==============================] - 7s 77ms/step - loss: 0.9584 - acc: 0.5497 - val_loss: 0.9711 - val_acc: 0.5526
Epoch 5/15
86/86 [==============================] - 1s 12ms/step - loss: 0.9577 - acc: 0.5585 - val_loss: 0.9736 - val_acc: 0.5263
Epoch 6/15
86/86 [==============================] - 1s 12ms/step - loss: 0.9518 - acc: 0.5534 - val_loss: 0.9765 - val_acc: 0.5329
Epoch 7/15
86/86 [==============================] - 1s 12ms/step - loss: 0.9514 - acc: 0.5482 - val_loss: 0.9672 - val_acc: 0.5461
Epoch 8/15
86/86 [==============================] - 1s 12ms/step - loss: 0.9474 - acc: 0.5526 - val_loss: 0.9746 - val_acc: 0.5526
Epoch 9/15
86/86 [==============================] - 1s 12ms/step - loss: 0.9522 - acc: 0.5461 - val_loss: 0.9689 - val_acc: 0.5329
Epoch 10/15
86/86 [==============================] - 1s 12ms/step - loss: 0.9462 - acc: 0.5512 - val_loss: 0.9833 - val_acc: 0.5219
Epoch 11/15
86/86 [==============================] - 1s 12ms/step - loss: 0.9505 - acc: 0.557

In [69]:
model = tf.keras.models.load_model('./res/T_model_AttBLSTM_wav2vec.tf')
pred = model.predict(np.asarray(w2v_embs['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 6ms/step
              precision    recall  f1-score   support

         Neg     0.5528    0.9919    0.7100       248
         Pos     0.5833    0.0500    0.0921       140
         Neu     0.0000    0.0000    0.0000        69

    accuracy                         0.5536       457
   macro avg     0.3787    0.3473    0.2674       457
weighted avg     0.4787    0.5536    0.4135       457

[[246   2   0]
 [133   7   0]
 [ 66   3   0]]


/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

In [39]:
x = Input((36,768))
h = Attention()([x, x])
h = Bidirectional(LSTM(64, return_sequences=False, return_state=False))(h)

res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_11"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_12 (InputLayer)          [(None, 36, 768)]    0           []                               
                                                                                                  
 attention_1 (Attention)        (None, 36, 768)      0           ['input_12[0][0]',               
                                                                  'input_12[0][0]']               
                                                                                                  
 bidirectional_7 (Bidirectional  (None, 128)         426496      ['attention_1[0][0]']            
 )                                                                                                
                                                                                           

In [40]:
callback_list = [ModelCheckpoint(filepath='./res/T_model_AttBLSTM_bert.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(bert_embs['train']), y=np.asarray(label['train']), batch_size=16, epochs=15, 
            validation_data=[np.asarray(bert_embs['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/15
85/86 [============================>.] - ETA: 0s - loss: 0.9614 - acc: 0.5632

INFO:tensorflow:Assets written to: ./res/T_model_AttBLSTM_bert.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_AttBLSTM_bert.tf/assets


86/86 [==============================] - 9s 88ms/step - loss: 0.9628 - acc: 0.5621 - val_loss: 0.9139 - val_acc: 0.5987
Epoch 2/15
85/86 [============================>.] - ETA: 0s - loss: 0.7875 - acc: 0.6647

INFO:tensorflow:Assets written to: ./res/T_model_AttBLSTM_bert.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_AttBLSTM_bert.tf/assets


86/86 [==============================] - 6s 74ms/step - loss: 0.7944 - acc: 0.6623 - val_loss: 0.9218 - val_acc: 0.6118
Epoch 3/15
86/86 [==============================] - 1s 17ms/step - loss: 0.6395 - acc: 0.7522 - val_loss: 0.9119 - val_acc: 0.5789
Epoch 4/15
86/86 [==============================] - 1s 17ms/step - loss: 0.3986 - acc: 0.8560 - val_loss: 1.1785 - val_acc: 0.5570
Epoch 5/15
86/86 [==============================] - 1s 17ms/step - loss: 0.1922 - acc: 0.9423 - val_loss: 1.3655 - val_acc: 0.5219
Epoch 6/15
86/86 [==============================] - 1s 17ms/step - loss: 0.0755 - acc: 0.9832 - val_loss: 1.8252 - val_acc: 0.5461
Epoch 7/15
86/86 [==============================] - 1s 17ms/step - loss: 0.0449 - acc: 0.9890 - val_loss: 1.9767 - val_acc: 0.5482
Epoch 8/15
86/86 [==============================] - 1s 17ms/step - loss: 0.0117 - acc: 1.0000 - val_loss: 2.1745 - val_acc: 0.5351
Epoch 9/15
86/86 [==============================] - 1s 17ms/step - loss: 0.0030 - acc: 1.0000 

In [68]:
model = tf.keras.models.load_model('./res/T_model_AttBLSTM_bert.tf')
pred = model.predict(np.asarray(bert_embs['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 10ms/step
              precision    recall  f1-score   support

         Neg     0.6353    0.8710    0.7347       248
         Pos     0.5726    0.4786    0.5214       140
         Neu     0.0000    0.0000    0.0000        69

    accuracy                         0.6193       457
   macro avg     0.4026    0.4498    0.4187       457
weighted avg     0.5202    0.6193    0.5584       457

[[216  32   0]
 [ 73  67   0]
 [ 51  18   0]]


/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

# Model 4

In [51]:
x = Input((36,100))
q = Conv1D(64, 3, 1)(x)
v = Conv1D(64, 3, 1)(x)
qv_attention = Attention()([q, v])

q = GlobalAveragePooling1D()(q)
qv_attention = GlobalAveragePooling1D()(qv_attention)
h = Concatenate()([q, qv_attention])
# h = Bidirectional(LSTM(64, return_sequences=False, return_state=False))(h)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_16"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_17 (InputLayer)          [(None, 36, 100)]    0           []                               
                                                                                                  
 conv1d_6 (Conv1D)              (None, 34, 64)       19264       ['input_17[0][0]']               
                                                                                                  
 conv1d_7 (Conv1D)              (None, 34, 64)       19264       ['input_17[0][0]']               
                                                                                                  
 attention_6 (Attention)        (None, 34, 64)       0           ['conv1d_6[0][0]',               
                                                                  'conv1d_7[0][0]']        

In [52]:
callback_list = [ModelCheckpoint(filepath='./res/T_model_AttCNN_wav2vec.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(w2v_embs['train']), y=np.asarray(label['train']), batch_size=16, epochs=15, 
            validation_data=[np.asarray(w2v_embs['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/15
78/86 [==========================>...] - ETA: 0s - loss: 0.9959 - acc: 0.5296

INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_wav2vec.tf/assets


86/86 [==============================] - 1s 9ms/step - loss: 0.9931 - acc: 0.5358 - val_loss: 0.9916 - val_acc: 0.5439
Epoch 2/15
86/86 [==============================] - 0s 3ms/step - loss: 0.9751 - acc: 0.5461 - val_loss: 0.9862 - val_acc: 0.5329
Epoch 3/15
82/86 [===========================>..] - ETA: 0s - loss: 0.9704 - acc: 0.5366

INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_wav2vec.tf/assets


86/86 [==============================] - 1s 7ms/step - loss: 0.9721 - acc: 0.5395 - val_loss: 0.9729 - val_acc: 0.5504
Epoch 4/15
86/86 [==============================] - 0s 3ms/step - loss: 0.9590 - acc: 0.5475 - val_loss: 0.9758 - val_acc: 0.5461
Epoch 5/15
86/86 [==============================] - 0s 3ms/step - loss: 0.9588 - acc: 0.5534 - val_loss: 0.9761 - val_acc: 0.5461
Epoch 6/15
86/86 [==============================] - ETA: 0s - loss: 0.9562 - acc: 0.5468

INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_wav2vec.tf/assets


86/86 [==============================] - 1s 7ms/step - loss: 0.9562 - acc: 0.5468 - val_loss: 0.9753 - val_acc: 0.5526
Epoch 7/15
86/86 [==============================] - 0s 3ms/step - loss: 0.9626 - acc: 0.5461 - val_loss: 0.9704 - val_acc: 0.5504
Epoch 8/15
86/86 [==============================] - 0s 3ms/step - loss: 0.9507 - acc: 0.5504 - val_loss: 0.9760 - val_acc: 0.5417
Epoch 9/15
86/86 [==============================] - 0s 3ms/step - loss: 0.9598 - acc: 0.5446 - val_loss: 0.9722 - val_acc: 0.5307
Epoch 10/15
80/86 [==========================>...] - ETA: 0s - loss: 0.9533 - acc: 0.5539

INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_wav2vec.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_wav2vec.tf/assets


86/86 [==============================] - 1s 7ms/step - loss: 0.9527 - acc: 0.5519 - val_loss: 0.9769 - val_acc: 0.5548
Epoch 11/15
86/86 [==============================] - 0s 3ms/step - loss: 0.9518 - acc: 0.5475 - val_loss: 0.9955 - val_acc: 0.5439
Epoch 12/15
86/86 [==============================] - 0s 3ms/step - loss: 0.9568 - acc: 0.5461 - val_loss: 0.9724 - val_acc: 0.5373
Epoch 13/15
86/86 [==============================] - 0s 3ms/step - loss: 0.9541 - acc: 0.5461 - val_loss: 0.9749 - val_acc: 0.5504
Epoch 14/15
86/86 [==============================] - 0s 3ms/step - loss: 0.9519 - acc: 0.5519 - val_loss: 0.9777 - val_acc: 0.5373
Epoch 15/15
86/86 [==============================] - 0s 3ms/step - loss: 0.9485 - acc: 0.5541 - val_loss: 0.9730 - val_acc: 0.5241


In [67]:
model = tf.keras.models.load_model('./res/T_model_AttCNN_wav2vec.tf')
pred = model.predict(np.asarray(w2v_embs['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 2ms/step
              precision    recall  f1-score   support

         Neg     0.5573    0.9798    0.7105       248
         Pos     0.4762    0.0714    0.1242       140
         Neu     0.0000    0.0000    0.0000        69

    accuracy                         0.5536       457
   macro avg     0.3445    0.3504    0.2782       457
weighted avg     0.4483    0.5536    0.4236       457

[[243   5   0]
 [130  10   0]
 [ 63   6   0]]


/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

In [59]:
x = Input((36,768))
q = Conv1D(64, 3, 1)(x)
v = Conv1D(64, 3, 1)(x)
qv_attention = Attention()([q, v])

q = GlobalAveragePooling1D()(q)
qv_attention = GlobalAveragePooling1D()(qv_attention)
h = Concatenate()([q, qv_attention])
# h = Bidirectional(LSTM(64, return_sequences=False, return_state=False))(h)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_18"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_19 (InputLayer)          [(None, 36, 768)]    0           []                               
                                                                                                  
 conv1d_10 (Conv1D)             (None, 34, 64)       147520      ['input_19[0][0]']               
                                                                                                  
 conv1d_11 (Conv1D)             (None, 34, 64)       147520      ['input_19[0][0]']               
                                                                                                  
 attention_8 (Attention)        (None, 34, 64)       0           ['conv1d_10[0][0]',              
                                                                  'conv1d_11[0][0]']       

In [60]:
callback_list = [ModelCheckpoint(filepath='./res/T_model_AttCNN_bert.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(bert_embs['train']), y=np.asarray(label['train']), batch_size=16, epochs=15, 
            validation_data=[np.asarray(bert_embs['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/15
80/86 [==========================>...] - ETA: 0s - loss: 0.9926 - acc: 0.5469

INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_bert.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_bert.tf/assets


86/86 [==============================] - 1s 12ms/step - loss: 0.9936 - acc: 0.5475 - val_loss: 0.9988 - val_acc: 0.5461
Epoch 2/15
81/86 [===========================>..] - ETA: 0s - loss: 0.7780 - acc: 0.6759

INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_bert.tf/assets


INFO:tensorflow:Assets written to: ./res/T_model_AttCNN_bert.tf/assets


86/86 [==============================] - 1s 11ms/step - loss: 0.7824 - acc: 0.6718 - val_loss: 0.9467 - val_acc: 0.6118
Epoch 3/15
86/86 [==============================] - 1s 6ms/step - loss: 0.6810 - acc: 0.7156 - val_loss: 1.0312 - val_acc: 0.5943
Epoch 4/15
86/86 [==============================] - 1s 6ms/step - loss: 0.6401 - acc: 0.7485 - val_loss: 1.0886 - val_acc: 0.5702
Epoch 5/15
86/86 [==============================] - 1s 6ms/step - loss: 0.5357 - acc: 0.7851 - val_loss: 1.1622 - val_acc: 0.5855
Epoch 6/15
86/86 [==============================] - 1s 6ms/step - loss: 0.4773 - acc: 0.8158 - val_loss: 1.3372 - val_acc: 0.5877
Epoch 7/15
86/86 [==============================] - 1s 6ms/step - loss: 0.4022 - acc: 0.8392 - val_loss: 1.6286 - val_acc: 0.5789
Epoch 8/15
86/86 [==============================] - 1s 6ms/step - loss: 0.3361 - acc: 0.8757 - val_loss: 1.5721 - val_acc: 0.5548
Epoch 9/15
86/86 [==============================] - 1s 6ms/step - loss: 0.2618 - acc: 0.9101 - val_l

In [66]:
model = tf.keras.models.load_model('./res/T_model_AttCNN_bert.tf')
pred = model.predict(np.asarray(bert_embs['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 3ms/step
              precision    recall  f1-score   support

         Neg     0.6506    0.8710    0.7448       248
         Pos     0.5743    0.4143    0.4813       140
         Neu     0.2917    0.1014    0.1505        69

    accuracy                         0.6149       457
   macro avg     0.5055    0.4622    0.4589       457
weighted avg     0.5730    0.6149    0.5744       457

[[216  26   6]
 [ 71  58  11]
 [ 45  17   7]]
