In [2]:
import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.layers import Input, Bidirectional, Dense, Conv1D, Conv3D, LSTM, ConvLSTM1D, ConvLSTM2D, Flatten, Concatenate, TimeDistributed
from utilz import *
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

2022-10-12 11:34:26.218976: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-12 11:34:26.305417: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-10-12 11:34:26.325928: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-12 11:34:26.715101: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: li

In [3]:
visual_ori = load_features('./data/visual_mpori.pkl')
visual_of = load_features('./data/visual_OFfts.pkl')
visual_clip = load_features('./data/visual_clip.pkl')
label = load_features('./data/labels.pkl')

In [22]:
print(np.shape(visual_ori['train']),
      np.shape(visual_of['train']),
      np.shape(visual_clip['train']))

(1368, 10, 64, 64) (1368, 30, 49) (1368, 10, 512)


# Model 1

In [4]:
x = Input((10, 64, 64, 1))
h = Conv3D(16, [3,3,3], [2,2,2], 'same')(x)
h = Conv3D(32, [1,1,1], [2,2,2], 'same')(h)
h = Conv3D(8, [3,3,3], [2,2,2], 'same')(h)

h = Flatten()(h)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 64, 64, 1)]   0         
                                                                 
 conv3d (Conv3D)             (None, 5, 32, 32, 16)     448       
                                                                 
 conv3d_1 (Conv3D)           (None, 3, 16, 16, 32)     544       
                                                                 
 conv3d_2 (Conv3D)           (None, 2, 8, 8, 8)        6920      
                                                                 
 flatten (Flatten)           (None, 1024)              0         
                                                                 
 dense (Dense)               (None, 3)                 3075      
                                                                 
Total params: 10,987
Trainable params: 10,987
Non-trainable p

2022-10-06 12:19:45.335570: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-06 12:19:45.363957: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-06 12:19:45.364100: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-06 12:19:45.364439: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compi

In [5]:
callback_list = [ModelCheckpoint(filepath='./res/V_model_CNN_mpori.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.expand_dims(visual_ori['train'], axis=-1), y=np.asarray(label['train']), batch_size=16, epochs=30, 
            validation_data=[np.expand_dims(visual_ori['valid'], axis=-1), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/30


2022-10-06 12:19:50.158569: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8500


 1/86 [..............................] - ETA: 2:10 - loss: 29.3258 - acc: 0.1875

2022-10-06 12:19:50.585265: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


71/86 [=======================>......] - ETA: 0s - loss: 8.6513 - acc: 0.4085

INFO:tensorflow:Assets written to: ./res/V_model_CNN_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_mpori.tf/assets


86/86 [==============================] - 2s 11ms/step - loss: 8.0662 - acc: 0.4072 - val_loss: 4.0373 - val_acc: 0.4781
Epoch 2/30
76/86 [=========================>....] - ETA: 0s - loss: 2.7394 - acc: 0.5173

INFO:tensorflow:Assets written to: ./res/V_model_CNN_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_mpori.tf/assets


86/86 [==============================] - 1s 7ms/step - loss: 2.7064 - acc: 0.5132 - val_loss: 3.2474 - val_acc: 0.4342
Epoch 3/30
76/86 [=========================>....] - ETA: 0s - loss: 1.5347 - acc: 0.6127

INFO:tensorflow:Assets written to: ./res/V_model_CNN_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_mpori.tf/assets


86/86 [==============================] - 1s 7ms/step - loss: 1.5546 - acc: 0.6111 - val_loss: 2.8864 - val_acc: 0.4781
Epoch 4/30
81/86 [===========================>..] - ETA: 0s - loss: 0.9711 - acc: 0.6952

INFO:tensorflow:Assets written to: ./res/V_model_CNN_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_mpori.tf/assets


86/86 [==============================] - 1s 7ms/step - loss: 0.9960 - acc: 0.6908 - val_loss: 2.7931 - val_acc: 0.4189
Epoch 5/30
71/86 [=======================>......] - ETA: 0s - loss: 0.6678 - acc: 0.7623

INFO:tensorflow:Assets written to: ./res/V_model_CNN_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_mpori.tf/assets


86/86 [==============================] - 1s 8ms/step - loss: 0.6754 - acc: 0.7610 - val_loss: 2.6713 - val_acc: 0.4320
Epoch 6/30
86/86 [==============================] - 0s 3ms/step - loss: 0.4920 - acc: 0.8077 - val_loss: 2.8357 - val_acc: 0.4649
Epoch 7/30
86/86 [==============================] - 0s 3ms/step - loss: 0.3632 - acc: 0.8662 - val_loss: 2.7742 - val_acc: 0.4276
Epoch 8/30
86/86 [==============================] - 0s 3ms/step - loss: 0.2591 - acc: 0.9057 - val_loss: 2.7736 - val_acc: 0.4320
Epoch 9/30
86/86 [==============================] - 0s 3ms/step - loss: 0.2105 - acc: 0.9247 - val_loss: 2.8930 - val_acc: 0.4496
Epoch 10/30
86/86 [==============================] - 0s 3ms/step - loss: 0.1716 - acc: 0.9459 - val_loss: 2.9733 - val_acc: 0.4408
Epoch 11/30
86/86 [==============================] - 0s 3ms/step - loss: 0.1184 - acc: 0.9722 - val_loss: 3.2057 - val_acc: 0.4232
Epoch 12/30
86/86 [==============================] - 0s 3ms/step - loss: 0.0917 - acc: 0.9817 - val

In [10]:
model = tf.keras.models.load_model('./res/V_model_CNN_mpori.tf/')
pred = model.predict(np.expand_dims(visual_ori['test'], axis=-1))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 2ms/step
              precision    recall  f1-score   support

         Neg     0.5294    0.4355    0.4779       248
         Pos     0.3046    0.3286    0.3162       140
         Neu     0.1275    0.1884    0.1520        69

    accuracy                         0.3654       457
   macro avg     0.3205    0.3175    0.3154       457
weighted avg     0.3999    0.3654    0.3791       457

[[108  82  58]
 [ 63  46  31]
 [ 33  23  13]]


In [60]:
x = Input((30, 49))
h = Conv1D(64, 3, 1, 'same')(x)
h = Conv1D(64, 1, 1, 'same')(h)
h = Conv1D(64, 3, 1, 'same')(h)
h = Flatten()(h)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_29"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_24 (InputLayer)       [(None, 30, 49)]          0         
                                                                 
 conv1d_1 (Conv1D)           (None, 30, 64)            9472      
                                                                 
 conv1d_2 (Conv1D)           (None, 30, 64)            4160      
                                                                 
 conv1d_3 (Conv1D)           (None, 30, 64)            12352     
                                                                 
 flatten_22 (Flatten)        (None, 1920)              0         
                                                                 
 dense_55 (Dense)            (None, 3)                 5763      
                                                                 
Total params: 31,747
Trainable params: 31,747
Non-trainabl

In [61]:
callback_list = [ModelCheckpoint(filepath='./res/V_model_CNN_of.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(visual_of['train']), y=np.asarray(label['train']), batch_size=16, epochs=30, 
            validation_data=[np.asarray(visual_of['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/30
86/86 [==============================] - ETA: 0s - loss: 32.5679 - acc: 0.4145

INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


86/86 [==============================] - 1s 10ms/step - loss: 32.5679 - acc: 0.4145 - val_loss: 4.5351 - val_acc: 0.3289
Epoch 2/30
86/86 [==============================] - 0s 2ms/step - loss: 5.0057 - acc: 0.4437 - val_loss: 9.1261 - val_acc: 0.1667
Epoch 3/30
73/86 [========================>.....] - ETA: 0s - loss: 4.5452 - acc: 0.4264

INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


86/86 [==============================] - 1s 6ms/step - loss: 4.3482 - acc: 0.4225 - val_loss: 3.2565 - val_acc: 0.3202
Epoch 4/30
81/86 [===========================>..] - ETA: 0s - loss: 2.7926 - acc: 0.4630

INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


86/86 [==============================] - 1s 7ms/step - loss: 2.8003 - acc: 0.4664 - val_loss: 2.0757 - val_acc: 0.3596
Epoch 5/30
86/86 [==============================] - 0s 5ms/step - loss: 2.1552 - acc: 0.4788 - val_loss: 2.2641 - val_acc: 0.4978
Epoch 6/30
86/86 [==============================] - 0s 4ms/step - loss: 2.1755 - acc: 0.4591 - val_loss: 2.2378 - val_acc: 0.5307
Epoch 7/30
67/86 [======================>.......] - ETA: 0s - loss: 1.9002 - acc: 0.4841

INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


86/86 [==============================] - 1s 6ms/step - loss: 1.8212 - acc: 0.4942 - val_loss: 1.6617 - val_acc: 0.4649
Epoch 8/30
86/86 [==============================] - 0s 2ms/step - loss: 1.8619 - acc: 0.5102 - val_loss: 2.0455 - val_acc: 0.5022
Epoch 9/30
86/86 [==============================] - 0s 2ms/step - loss: 1.7553 - acc: 0.4971 - val_loss: 2.1099 - val_acc: 0.3399
Epoch 10/30
86/86 [==============================] - 0s 2ms/step - loss: 1.2520 - acc: 0.5629 - val_loss: 1.9239 - val_acc: 0.5219
Epoch 11/30
86/86 [==============================] - 0s 2ms/step - loss: 1.2708 - acc: 0.5658 - val_loss: 2.0730 - val_acc: 0.3728
Epoch 12/30
86/86 [==============================] - 0s 2ms/step - loss: 1.0637 - acc: 0.5921 - val_loss: 1.8695 - val_acc: 0.4408
Epoch 13/30
86/86 [==============================] - 0s 2ms/step - loss: 2.6421 - acc: 0.5044 - val_loss: 7.6545 - val_acc: 0.3311
Epoch 14/30
62/86 [====================>.........] - ETA: 0s - loss: 1.7527 - acc: 0.5464

INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


86/86 [==============================] - 1s 6ms/step - loss: 1.5575 - acc: 0.5673 - val_loss: 1.6044 - val_acc: 0.5219
Epoch 15/30
64/86 [=====================>........] - ETA: 0s - loss: 0.9546 - acc: 0.6357

INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_of.tf/assets


86/86 [==============================] - 1s 6ms/step - loss: 0.9721 - acc: 0.6287 - val_loss: 1.3928 - val_acc: 0.5504
Epoch 16/30
86/86 [==============================] - 0s 2ms/step - loss: 0.9603 - acc: 0.6396 - val_loss: 1.6377 - val_acc: 0.4890
Epoch 17/30
86/86 [==============================] - 0s 2ms/step - loss: 0.9065 - acc: 0.6411 - val_loss: 1.8931 - val_acc: 0.5461
Epoch 18/30
86/86 [==============================] - 0s 2ms/step - loss: 1.0143 - acc: 0.6279 - val_loss: 1.4633 - val_acc: 0.5022
Epoch 19/30
86/86 [==============================] - 0s 2ms/step - loss: 0.9988 - acc: 0.6557 - val_loss: 2.0323 - val_acc: 0.3684
Epoch 20/30
86/86 [==============================] - 0s 2ms/step - loss: 0.9491 - acc: 0.6411 - val_loss: 2.5594 - val_acc: 0.5329
Epoch 21/30
86/86 [==============================] - 0s 2ms/step - loss: 0.9588 - acc: 0.6396 - val_loss: 1.8058 - val_acc: 0.4956
Epoch 22/30
86/86 [==============================] - 0s 2ms/step - loss: 1.0515 - acc: 0.6265 -

In [63]:
model = tf.keras.models.load_model('./res/V_model_CNN_of.tf/')
pred = model.predict(np.asarray(visual_of['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 3ms/step
              precision    recall  f1-score   support

         Neg     0.5800    0.8185    0.6789       248
         Pos     0.5647    0.3429    0.4267       140
         Neu     0.0455    0.0145    0.0220        69

    accuracy                         0.5514       457
   macro avg     0.3967    0.3920    0.3759       457
weighted avg     0.4946    0.5514    0.5025       457

[[203  32  13]
 [ 84  48   8]
 [ 63   5   1]]


In [64]:
x = Input((10, 512))
h = Conv1D(64, 3, 1, 'same')(x)
h = Conv1D(64, 1, 1, 'same')(h)
h = Conv1D(64, 3, 1, 'same')(h)
h = Flatten()(h)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_30"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_25 (InputLayer)       [(None, 10, 512)]         0         
                                                                 
 conv1d_4 (Conv1D)           (None, 10, 64)            98368     
                                                                 
 conv1d_5 (Conv1D)           (None, 10, 64)            4160      
                                                                 
 conv1d_6 (Conv1D)           (None, 10, 64)            12352     
                                                                 
 flatten_23 (Flatten)        (None, 640)               0         
                                                                 
 dense_56 (Dense)            (None, 3)                 1923      
                                                                 
Total params: 116,803
Trainable params: 116,803
Non-traina

In [65]:
callback_list = [ModelCheckpoint(filepath='./res/V_model_CNN_clip.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(visual_clip['train']), y=np.asarray(label['train']), batch_size=16, epochs=30, 
            validation_data=[np.asarray(visual_clip['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/30
86/86 [==============================] - ETA: 0s - loss: 1.0114 - acc: 0.5322

INFO:tensorflow:Assets written to: ./res/V_model_CNN_clip.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_clip.tf/assets


86/86 [==============================] - 1s 10ms/step - loss: 1.0114 - acc: 0.5322 - val_loss: 0.9768 - val_acc: 0.5921
Epoch 2/30
71/86 [=======================>......] - ETA: 0s - loss: 0.7901 - acc: 0.6549

INFO:tensorflow:Assets written to: ./res/V_model_CNN_clip.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNN_clip.tf/assets


86/86 [==============================] - 1s 7ms/step - loss: 0.7865 - acc: 0.6550 - val_loss: 0.9093 - val_acc: 0.5899
Epoch 3/30
86/86 [==============================] - 0s 4ms/step - loss: 0.6385 - acc: 0.7325 - val_loss: 0.9950 - val_acc: 0.5921
Epoch 4/30
86/86 [==============================] - 0s 5ms/step - loss: 0.4983 - acc: 0.8034 - val_loss: 1.1365 - val_acc: 0.5351
Epoch 5/30
86/86 [==============================] - 0s 5ms/step - loss: 0.3582 - acc: 0.8713 - val_loss: 1.3861 - val_acc: 0.5285
Epoch 6/30
86/86 [==============================] - 0s 4ms/step - loss: 0.2568 - acc: 0.9167 - val_loss: 1.5751 - val_acc: 0.5351
Epoch 7/30
86/86 [==============================] - 0s 2ms/step - loss: 0.1673 - acc: 0.9393 - val_loss: 1.8574 - val_acc: 0.5219
Epoch 8/30
86/86 [==============================] - 0s 2ms/step - loss: 0.1352 - acc: 0.9539 - val_loss: 2.3118 - val_acc: 0.5088
Epoch 9/30
86/86 [==============================] - 0s 2ms/step - loss: 0.0803 - acc: 0.9788 - val_lo

In [66]:
model = tf.keras.models.load_model('./res/V_model_CNN_clip.tf/')
pred = model.predict(np.asarray(visual_clip['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 2ms/step
              precision    recall  f1-score   support

         Neg     0.6700    0.8185    0.7368       248
         Pos     0.5571    0.5571    0.5571       140
         Neu     0.1429    0.0290    0.0482        69

    accuracy                         0.6193       457
   macro avg     0.4567    0.4682    0.4474       457
weighted avg     0.5558    0.6193    0.5778       457

[[203  39   6]
 [ 56  78   6]
 [ 44  23   2]]


# Model 2

In [23]:
x = Input((10, 64, 64, 1))
h = ConvLSTM2D(16, [3,3], [2,2], 'same', return_sequences=True)(x)
h = TimeDistributed(Flatten())(h)
h = LSTM(64, activation='relu')(h)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_8 (InputLayer)        [(None, 10, 64, 64, 1)]   0         
                                                                 
 conv_lstm2d_7 (ConvLSTM2D)  (None, 10, 32, 32, 16)    9856      
                                                                 
 time_distributed_4 (TimeDis  (None, 10, 16384)        0         
 tributed)                                                       
                                                                 
 lstm_2 (LSTM)               (None, 64)                4210944   
                                                                 
 dense_10 (Dense)            (None, 3)                 195       
                                                                 
Total params: 4,220,995
Trainable params: 4,220,995
Non-trainable params: 0
________________________________________________

In [24]:
callback_list = [ModelCheckpoint(filepath='./res/V_model_CNNLSTM_mpori.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.expand_dims(visual_ori['train'], axis=-1), y=np.asarray(label['train']), batch_size=16, epochs=30, 
            validation_data=[np.expand_dims(visual_ori['valid'], axis=-1), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/30
86/86 [==============================] - ETA: 0s - loss: 1.7863 - acc: 0.4825INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_mpori.tf/assets


86/86 [==============================] - 7s 65ms/step - loss: 1.7863 - acc: 0.4825 - val_loss: 1.0580 - val_acc: 0.5044
Epoch 2/30
85/86 [============================>.] - ETA: 0s - loss: 0.7934 - acc: 0.6551INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_mpori.tf/assets


86/86 [==============================] - 5s 56ms/step - loss: 0.7935 - acc: 0.6542 - val_loss: 1.0413 - val_acc: 0.5044
Epoch 3/30
86/86 [==============================] - 3s 34ms/step - loss: 0.5683 - acc: 0.7763 - val_loss: 1.2113 - val_acc: 0.5219
Epoch 4/30
86/86 [==============================] - 3s 33ms/step - loss: 0.3272 - acc: 0.8984 - val_loss: 1.2213 - val_acc: 0.4759
Epoch 5/30
86/86 [==============================] - 3s 37ms/step - loss: 0.2196 - acc: 0.9430 - val_loss: 1.5425 - val_acc: 0.4978
Epoch 6/30
86/86 [==============================] - 3s 38ms/step - loss: 0.1923 - acc: 0.9539 - val_loss: 1.6878 - val_acc: 0.5351
Epoch 7/30
86/86 [==============================] - 3s 40ms/step - loss: 0.1182 - acc: 0.9744 - val_loss: 1.7958 - val_acc: 0.4232
Epoch 8/30
86/86 [==============================] - 3s 39ms/step - loss: 0.0586 - acc: 0.9905 - val_loss: 1.9997 - val_acc: 0.4803
Epoch 9/30
86/86 [==============================] - 3s 34ms/step - loss: 0.0264 - acc: 0.9920 

In [25]:
model = tf.keras.models.load_model('./res/V_model_CNNLSTM_mpori.tf/')
pred = model.predict(np.expand_dims(visual_ori['test'], axis=-1))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 10ms/step
              precision    recall  f1-score   support

         Neg     0.5681    0.7903    0.6610       248
         Pos     0.3553    0.1929    0.2500       140
         Neu     0.2500    0.1304    0.1714        69

    accuracy                         0.5077       457
   macro avg     0.3911    0.3712    0.3608       457
weighted avg     0.4549    0.5077    0.4612       457

[[196  33  19]
 [105  27   8]
 [ 44  16   9]]


In [92]:
x = Input((30, 49))
h = Conv1D(64, 3, 1, 'same')(x)
h = Conv1D(64, 1, 1, 'same')(h)
h = Conv1D(64, 3, 1, 'same')(h)
h = LSTM(64, activation='relu')(h)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_39"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_35 (InputLayer)       [(None, 30, 49)]          0         
                                                                 
 conv1d_30 (Conv1D)          (None, 30, 64)            9472      
                                                                 
 conv1d_31 (Conv1D)          (None, 30, 64)            4160      
                                                                 
 conv1d_32 (Conv1D)          (None, 30, 64)            12352     
                                                                 
 lstm_20 (LSTM)              (None, 64)                33024     
                                                                 
 dense_65 (Dense)            (None, 3)                 195       
                                                                 
Total params: 59,203
Trainable params: 59,203
Non-trainabl

In [93]:
callback_list = [ModelCheckpoint(filepath='./res/V_model_CNNLSTM_of.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(visual_of['train']), y=np.asarray(label['train']), batch_size=16, epochs=30, 
            validation_data=[np.asarray(visual_of['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/30
85/86 [============================>.] - ETA: 0s - loss: 1429.7815 - acc: 0.3603

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 5s 50ms/step - loss: 1424.3860 - acc: 0.3604 - val_loss: 710.1916 - val_acc: 0.3947
Epoch 2/30
86/86 [==============================] - ETA: 0s - loss: 557.7405 - acc: 0.4050

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 3s 30ms/step - loss: 557.7405 - acc: 0.4050 - val_loss: 618.5760 - val_acc: 0.4496
Epoch 3/30
85/86 [============================>.] - ETA: 0s - loss: 959.3793 - acc: 0.4301

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 2s 29ms/step - loss: 956.0035 - acc: 0.4306 - val_loss: 280.2760 - val_acc: 0.4978
Epoch 4/30
86/86 [==============================] - 2s 19ms/step - loss: 352.0861 - acc: 0.4145 - val_loss: 451.1417 - val_acc: 0.4605
Epoch 5/30
86/86 [==============================] - 2s 19ms/step - loss: 418.3564 - acc: 0.4115 - val_loss: 775.7912 - val_acc: 0.3202
Epoch 6/30
86/86 [==============================] - 2s 19ms/step - loss: 1829.1564 - acc: 0.4218 - val_loss: 1817.4990 - val_acc: 0.4013
Epoch 7/30
86/86 [==============================] - ETA: 0s - loss: 1224.6788 - acc: 0.3713

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 3s 30ms/step - loss: 1224.6788 - acc: 0.3713 - val_loss: 124.8106 - val_acc: 0.3070
Epoch 8/30
86/86 [==============================] - ETA: 0s - loss: 45.7878 - acc: 0.4313

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 3s 29ms/step - loss: 45.7878 - acc: 0.4313 - val_loss: 34.4823 - val_acc: 0.3553
Epoch 9/30
85/86 [============================>.] - ETA: 0s - loss: 40.3192 - acc: 0.4294

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 2s 29ms/step - loss: 40.1898 - acc: 0.4298 - val_loss: 28.8737 - val_acc: 0.3553
Epoch 10/30
84/86 [============================>.] - ETA: 0s - loss: 32.0487 - acc: 0.4286

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 3s 29ms/step - loss: 31.9829 - acc: 0.4291 - val_loss: 25.7856 - val_acc: 0.3487
Epoch 11/30
86/86 [==============================] - ETA: 0s - loss: 31.4344 - acc: 0.4525

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 2s 29ms/step - loss: 31.4344 - acc: 0.4525 - val_loss: 24.1268 - val_acc: 0.3355
Epoch 12/30
85/86 [============================>.] - ETA: 0s - loss: 29.6709 - acc: 0.4294

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 3s 30ms/step - loss: 29.5613 - acc: 0.4306 - val_loss: 22.0865 - val_acc: 0.4013
Epoch 13/30
86/86 [==============================] - 2s 19ms/step - loss: 27.5444 - acc: 0.4189 - val_loss: 26.6788 - val_acc: 0.4956
Epoch 14/30
86/86 [==============================] - 2s 19ms/step - loss: 28.8970 - acc: 0.4335 - val_loss: 28.7928 - val_acc: 0.3070
Epoch 15/30
84/86 [============================>.] - ETA: 0s - loss: 24.3255 - acc: 0.4330

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 3s 29ms/step - loss: 24.8161 - acc: 0.4342 - val_loss: 17.8001 - val_acc: 0.4167
Epoch 16/30
86/86 [==============================] - 2s 18ms/step - loss: 24.2241 - acc: 0.4532 - val_loss: 31.0496 - val_acc: 0.5000
Epoch 17/30
86/86 [==============================] - 2s 18ms/step - loss: 22.9004 - acc: 0.4591 - val_loss: 19.3540 - val_acc: 0.3969
Epoch 18/30
86/86 [==============================] - 1s 17ms/step - loss: 24.8245 - acc: 0.4349 - val_loss: 22.9970 - val_acc: 0.4232
Epoch 19/30
86/86 [==============================] - 2s 18ms/step - loss: 20.0119 - acc: 0.4613 - val_loss: 18.1662 - val_acc: 0.4232
Epoch 20/30
86/86 [==============================] - 2s 19ms/step - loss: 23.5575 - acc: 0.4357 - val_loss: 17.8937 - val_acc: 0.3882
Epoch 21/30
84/86 [============================>.] - ETA: 0s - loss: 23.0713 - acc: 0.4234

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 2s 29ms/step - loss: 22.8675 - acc: 0.4240 - val_loss: 14.5491 - val_acc: 0.4167
Epoch 22/30
86/86 [==============================] - 2s 19ms/step - loss: 17.8388 - acc: 0.4561 - val_loss: 22.2007 - val_acc: 0.3684
Epoch 23/30
86/86 [==============================] - 2s 18ms/step - loss: 21.9269 - acc: 0.4408 - val_loss: 19.8914 - val_acc: 0.4781
Epoch 24/30
85/86 [============================>.] - ETA: 0s - loss: 17.2138 - acc: 0.4544

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 3s 29ms/step - loss: 17.1485 - acc: 0.4547 - val_loss: 13.7250 - val_acc: 0.3904
Epoch 25/30
86/86 [==============================] - 2s 19ms/step - loss: 19.9645 - acc: 0.4466 - val_loss: 18.5867 - val_acc: 0.5175
Epoch 26/30
86/86 [==============================] - 2s 20ms/step - loss: 16.2776 - acc: 0.4335 - val_loss: 15.6038 - val_acc: 0.4890
Epoch 27/30
86/86 [==============================] - 2s 20ms/step - loss: 17.4524 - acc: 0.4444 - val_loss: 17.1900 - val_acc: 0.4978
Epoch 28/30
86/86 [==============================] - 2s 19ms/step - loss: 13.7274 - acc: 0.4349 - val_loss: 15.2358 - val_acc: 0.5066
Epoch 29/30
86/86 [==============================] - 2s 20ms/step - loss: 12.5611 - acc: 0.4444 - val_loss: 15.6363 - val_acc: 0.3925
Epoch 30/30
84/86 [============================>.] - ETA: 0s - loss: 17.4361 - acc: 0.4159

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_of.tf/assets


86/86 [==============================] - 3s 29ms/step - loss: 17.2630 - acc: 0.4181 - val_loss: 11.8334 - val_acc: 0.4759


In [94]:
model = tf.keras.models.load_model('./res/V_model_CNNLSTM_of.tf/')
pred = model.predict(np.asarray(visual_of['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 5ms/step
              precision    recall  f1-score   support

         Neg     0.5670    0.8185    0.6700       248
         Pos     0.3816    0.2071    0.2685       140
         Neu     0.0435    0.0145    0.0217        69

    accuracy                         0.5098       457
   macro avg     0.3307    0.3467    0.3201       457
weighted avg     0.4312    0.5098    0.4491       457

[[203  31  14]
 [103  29   8]
 [ 52  16   1]]


In [95]:
x = Input((10, 512))
h = Conv1D(64, 3, 1, 'same')(x)
h = Conv1D(64, 1, 1, 'same')(h)
h = Conv1D(64, 3, 1, 'same')(h)
h = LSTM(64, activation='relu')(h)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_40"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_36 (InputLayer)       [(None, 10, 512)]         0         
                                                                 
 conv1d_33 (Conv1D)          (None, 10, 64)            98368     
                                                                 
 conv1d_34 (Conv1D)          (None, 10, 64)            4160      
                                                                 
 conv1d_35 (Conv1D)          (None, 10, 64)            12352     
                                                                 
 lstm_21 (LSTM)              (None, 64)                33024     
                                                                 
 dense_66 (Dense)            (None, 3)                 195       
                                                                 
Total params: 148,099
Trainable params: 148,099
Non-traina

In [96]:
callback_list = [ModelCheckpoint(filepath='./res/V_model_CNNLSTM_clip.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(visual_clip['train']), y=np.asarray(label['train']), batch_size=16, epochs=30, 
            validation_data=[np.asarray(visual_clip['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/30
81/86 [===========================>..] - ETA: 0s - loss: 0.9608 - acc: 0.5509

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_clip.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_clip.tf/assets


86/86 [==============================] - 2s 22ms/step - loss: 0.9507 - acc: 0.5548 - val_loss: 0.9078 - val_acc: 0.5877
Epoch 2/30
86/86 [==============================] - 1s 11ms/step - loss: 0.8625 - acc: 0.6323 - val_loss: 0.9237 - val_acc: 0.5921
Epoch 3/30
86/86 [==============================] - 1s 13ms/step - loss: 0.8213 - acc: 0.6637 - val_loss: 0.9559 - val_acc: 0.5636
Epoch 4/30
86/86 [==============================] - 1s 14ms/step - loss: 0.7717 - acc: 0.6762 - val_loss: 1.0107 - val_acc: 0.6206
Epoch 5/30
85/86 [============================>.] - ETA: 0s - loss: 0.7520 - acc: 0.6794

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_clip.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_clip.tf/assets


86/86 [==============================] - 2s 22ms/step - loss: 0.7521 - acc: 0.6798 - val_loss: 0.8990 - val_acc: 0.6184
Epoch 6/30
86/86 [==============================] - ETA: 0s - loss: 0.7100 - acc: 0.6820

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_clip.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTM_clip.tf/assets


86/86 [==============================] - 2s 23ms/step - loss: 0.7100 - acc: 0.6820 - val_loss: 0.8728 - val_acc: 0.6250
Epoch 7/30
86/86 [==============================] - 1s 10ms/step - loss: 0.6748 - acc: 0.7127 - val_loss: 0.9418 - val_acc: 0.6031
Epoch 8/30
86/86 [==============================] - 1s 13ms/step - loss: 0.6331 - acc: 0.7222 - val_loss: 0.9458 - val_acc: 0.6096
Epoch 9/30
86/86 [==============================] - 1s 11ms/step - loss: 0.6093 - acc: 0.7332 - val_loss: 0.9933 - val_acc: 0.5855
Epoch 10/30
86/86 [==============================] - 1s 10ms/step - loss: 0.5692 - acc: 0.7500 - val_loss: 1.1048 - val_acc: 0.5987
Epoch 11/30
86/86 [==============================] - 1s 10ms/step - loss: 0.5635 - acc: 0.7463 - val_loss: 1.5224 - val_acc: 0.6228
Epoch 12/30
86/86 [==============================] - 1s 10ms/step - loss: 0.5820 - acc: 0.7485 - val_loss: 1.0548 - val_acc: 0.6075
Epoch 13/30
86/86 [==============================] - 1s 10ms/step - loss: 0.5111 - acc: 0.7

In [98]:
model = tf.keras.models.load_model('./res/V_model_CNNLSTM_clip.tf/')
pred = model.predict(np.asarray(visual_clip['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 2ms/step
              precision    recall  f1-score   support

         Neg     0.6210    0.9315    0.7452       248
         Pos     0.6849    0.3571    0.4695       140
         Neu     0.5000    0.0870    0.1481        69

    accuracy                         0.6280       457
   macro avg     0.6020    0.4585    0.4543       457
weighted avg     0.6223    0.6280    0.5706       457

[[231  13   4]
 [ 88  50   2]
 [ 53  10   6]]


# Model 3

In [5]:
class Attention_Self(tf.keras.layers.Layer):
    def __init__(self, units, **kwargs):
        super(Attention_Self, self).__init__(**kwargs)
        self.W1 = tf.keras.layers.Dense(units)
        self.W2 = tf.keras.layers.Dense(units)
        self.S = tf.keras.layers.Dense(1)
        self.units = units

    def call(self, features):
        features_ = tf.expand_dims(features, 1)
        v = self.W1(features)
        q =  self.W2(features_)
        score = tf.nn.tanh(q + v)
        attention_weights = tf.nn.softmax(self.S(score), axis=1)
        # ATTN = attention_weights * (v)
        ATTN = attention_weights * (v)
        ATTN = tf.reduce_sum(ATTN, axis=1)
        
        return ATTN
        
    def get_config(self):
        config = super(Attention_Self, self).get_config()
        config.update({"units": self.units})
        return config

In [52]:
x = Input((10, 64, 64, 1))
h = ConvLSTM2D(16, [3,3], [2,2], 'same', return_sequences=True)(x)
h = Attention_Self(16)(h)
h = TimeDistributed(Flatten())(h)
h = LSTM(64, activation='relu')(h)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_28"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_20 (InputLayer)       [(None, 10, 64, 64, 1)]   0         
                                                                 
 conv_lstm2d_19 (ConvLSTM2D)  (None, 10, 32, 32, 16)   9856      
                                                                 
 attention__self_11 (Attenti  (None, 10, 32, 32, 16)   561       
 on_Self)                                                        
                                                                 
 time_distributed_16 (TimeDi  (None, 10, 16384)        0         
 stributed)                                                      
                                                                 
 lstm_10 (LSTM)              (None, 64)                4210944   
                                                                 
 dense_54 (Dense)            (None, 3)                 195

In [53]:
callback_list = [ModelCheckpoint(filepath='./res/V_model_CNNLSTMAtt_mpori.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.expand_dims(visual_ori['train'], axis=-1), y=np.asarray(label['train']), batch_size=16, epochs=30, 
            validation_data=[np.expand_dims(visual_ori['valid'], axis=-1), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/30
85/86 [============================>.] - ETA: 0s - loss: 1.8604 - acc: 0.4926

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


86/86 [==============================] - 8s 78ms/step - loss: 1.8545 - acc: 0.4942 - val_loss: 1.0729 - val_acc: 0.5044
Epoch 2/30
86/86 [==============================] - ETA: 0s - loss: 1.0093 - acc: 0.5358

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


86/86 [==============================] - 7s 79ms/step - loss: 1.0093 - acc: 0.5358 - val_loss: 1.0476 - val_acc: 0.5417
Epoch 3/30
85/86 [============================>.] - ETA: 0s - loss: 0.9911 - acc: 0.5434

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


86/86 [==============================] - 6s 74ms/step - loss: 0.9914 - acc: 0.5424 - val_loss: 0.9963 - val_acc: 0.5439
Epoch 4/30
86/86 [==============================] - ETA: 0s - loss: 0.9917 - acc: 0.5424

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


86/86 [==============================] - 6s 76ms/step - loss: 0.9917 - acc: 0.5424 - val_loss: 0.9914 - val_acc: 0.5439
Epoch 5/30
86/86 [==============================] - 4s 51ms/step - loss: 0.9841 - acc: 0.5351 - val_loss: 0.9955 - val_acc: 0.5329
Epoch 6/30
86/86 [==============================] - 5s 55ms/step - loss: 0.9847 - acc: 0.5424 - val_loss: 1.0155 - val_acc: 0.5439
Epoch 7/30
86/86 [==============================] - 5s 55ms/step - loss: 0.9823 - acc: 0.5424 - val_loss: 0.9937 - val_acc: 0.5285
Epoch 8/30
86/86 [==============================] - 5s 54ms/step - loss: 0.9835 - acc: 0.5424 - val_loss: 0.9916 - val_acc: 0.5439
Epoch 9/30
86/86 [==============================] - 5s 53ms/step - loss: 0.9792 - acc: 0.5424 - val_loss: 0.9963 - val_acc: 0.5439
Epoch 10/30
86/86 [==============================] - ETA: 0s - loss: 0.9896 - acc: 0.5424

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


86/86 [==============================] - 7s 76ms/step - loss: 0.9896 - acc: 0.5424 - val_loss: 0.9840 - val_acc: 0.5439
Epoch 11/30
86/86 [==============================] - 4s 46ms/step - loss: 1.0040 - acc: 0.5424 - val_loss: 0.9908 - val_acc: 0.5439
Epoch 12/30
86/86 [==============================] - ETA: 0s - loss: 0.9876 - acc: 0.5424

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


86/86 [==============================] - 6s 68ms/step - loss: 0.9876 - acc: 0.5424 - val_loss: 0.9830 - val_acc: 0.5439
Epoch 13/30
86/86 [==============================] - ETA: 0s - loss: 0.9812 - acc: 0.5424

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_mpori.tf/assets


86/86 [==============================] - 6s 75ms/step - loss: 0.9812 - acc: 0.5424 - val_loss: 0.9814 - val_acc: 0.5439
Epoch 14/30
86/86 [==============================] - 5s 54ms/step - loss: 1.0139 - acc: 0.5395 - val_loss: 0.9882 - val_acc: 0.5439
Epoch 15/30
86/86 [==============================] - 4s 52ms/step - loss: 0.9956 - acc: 0.5395 - val_loss: 0.9894 - val_acc: 0.5439
Epoch 16/30
86/86 [==============================] - 4s 45ms/step - loss: 0.9980 - acc: 0.5424 - val_loss: 0.9873 - val_acc: 0.5439
Epoch 17/30
86/86 [==============================] - 4s 45ms/step - loss: 0.9879 - acc: 0.5424 - val_loss: 1.0246 - val_acc: 0.5395
Epoch 18/30
86/86 [==============================] - 4s 45ms/step - loss: 0.9899 - acc: 0.5424 - val_loss: 1.0287 - val_acc: 0.5439
Epoch 19/30
86/86 [==============================] - 4s 45ms/step - loss: 0.9819 - acc: 0.5424 - val_loss: 0.9910 - val_acc: 0.5439
Epoch 20/30
86/86 [==============================] - 4s 47ms/step - loss: 0.9834 - acc: 

In [55]:
model = tf.keras.models.load_model('./res/V_model_CNNLSTMAtt_mpori.tf/')
pred = model.predict(np.expand_dims(visual_ori['test'], axis=-1))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 1s 27ms/step
              precision    recall  f1-score   support

         Neg     0.5427    1.0000    0.7035       248
         Pos     0.0000    0.0000    0.0000       140
         Neu     0.0000    0.0000    0.0000        69

    accuracy                         0.5427       457
   macro avg     0.1809    0.3333    0.2345       457
weighted avg     0.2945    0.5427    0.3818       457

[[248   0   0]
 [140   0   0]
 [ 69   0   0]]


/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

In [17]:
x = Input((30, 49))
h = Attention_Self(64)(x)
h = Conv1D(64, 3, 1, 'same')(h)
h = Conv1D(64, 1, 1, 'same')(h)
h = Conv1D(64, 3, 1, 'same')(h)
h = LSTM(64, activation='relu')(h)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 30, 49)]          0         
                                                                 
 attention__self_4 (Attentio  (None, 30, 64)           6465      
 n_Self)                                                         
                                                                 
 conv1d_12 (Conv1D)          (None, 30, 64)            12352     
                                                                 
 conv1d_13 (Conv1D)          (None, 30, 64)            4160      
                                                                 
 conv1d_14 (Conv1D)          (None, 30, 64)            12352     
                                                                 
 lstm_6 (LSTM)               (None, 64)                33024     
                                                           

In [18]:
callback_list = [ModelCheckpoint(filepath='./res/V_model_CNNLSTMAtt_of.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(visual_of['train']), y=np.asarray(label['train']), batch_size=16, epochs=30, 
            validation_data=[np.asarray(visual_of['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/30
84/86 [============================>.] - ETA: 0s - loss: 56.4657 - acc: 0.3460

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 4s 38ms/step - loss: 55.5201 - acc: 0.3465 - val_loss: 1.8686 - val_acc: 0.4890
Epoch 2/30
83/86 [===========================>..] - ETA: 0s - loss: 1.3809 - acc: 0.4239

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 35ms/step - loss: 1.3838 - acc: 0.4284 - val_loss: 1.3939 - val_acc: 0.5088
Epoch 3/30
86/86 [==============================] - 2s 21ms/step - loss: 1.2762 - acc: 0.4635 - val_loss: 1.4068 - val_acc: 0.3947
Epoch 4/30
86/86 [==============================] - ETA: 0s - loss: 1.2978 - acc: 0.4466

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 38ms/step - loss: 1.2978 - acc: 0.4466 - val_loss: 1.3806 - val_acc: 0.4298
Epoch 5/30
84/86 [============================>.] - ETA: 0s - loss: 1.2437 - acc: 0.4658

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 35ms/step - loss: 1.2441 - acc: 0.4656 - val_loss: 1.3614 - val_acc: 0.5088
Epoch 6/30
85/86 [============================>.] - ETA: 0s - loss: 1.1764 - acc: 0.4625

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 35ms/step - loss: 1.1754 - acc: 0.4620 - val_loss: 1.3411 - val_acc: 0.4825
Epoch 7/30
86/86 [==============================] - 2s 22ms/step - loss: 1.2149 - acc: 0.4795 - val_loss: 1.3517 - val_acc: 0.4693
Epoch 8/30
86/86 [==============================] - 2s 22ms/step - loss: 1.1910 - acc: 0.4708 - val_loss: 1.5039 - val_acc: 0.3904
Epoch 9/30
86/86 [==============================] - 2s 22ms/step - loss: 1.1980 - acc: 0.4525 - val_loss: 1.4221 - val_acc: 0.4978
Epoch 10/30
85/86 [============================>.] - ETA: 0s - loss: 1.2117 - acc: 0.4647

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 36ms/step - loss: 1.2104 - acc: 0.4656 - val_loss: 1.3266 - val_acc: 0.4737
Epoch 11/30
86/86 [==============================] - 2s 22ms/step - loss: 1.3022 - acc: 0.4357 - val_loss: 1.3400 - val_acc: 0.5066
Epoch 12/30
86/86 [==============================] - 2s 21ms/step - loss: 1.1742 - acc: 0.4773 - val_loss: 1.4435 - val_acc: 0.3947
Epoch 13/30
86/86 [==============================] - 2s 22ms/step - loss: 1.2091 - acc: 0.4671 - val_loss: 1.3469 - val_acc: 0.3947
Epoch 14/30
86/86 [==============================] - 2s 21ms/step - loss: 1.1558 - acc: 0.4642 - val_loss: 1.3596 - val_acc: 0.5044
Epoch 15/30
86/86 [==============================] - ETA: 0s - loss: 1.1421 - acc: 0.4803

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 38ms/step - loss: 1.1421 - acc: 0.4803 - val_loss: 1.2902 - val_acc: 0.4934
Epoch 16/30
84/86 [============================>.] - ETA: 0s - loss: 1.1459 - acc: 0.4829

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 34ms/step - loss: 1.1522 - acc: 0.4825 - val_loss: 1.2882 - val_acc: 0.5154
Epoch 17/30
85/86 [============================>.] - ETA: 0s - loss: 1.1243 - acc: 0.4941

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 33ms/step - loss: 1.1268 - acc: 0.4942 - val_loss: 1.2768 - val_acc: 0.4978
Epoch 18/30
84/86 [============================>.] - ETA: 0s - loss: 1.1110 - acc: 0.4896

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 38ms/step - loss: 1.1244 - acc: 0.4876 - val_loss: 1.2696 - val_acc: 0.4737
Epoch 19/30
86/86 [==============================] - 2s 21ms/step - loss: 1.1403 - acc: 0.4671 - val_loss: 1.2766 - val_acc: 0.5022
Epoch 20/30
86/86 [==============================] - 2s 20ms/step - loss: 1.1329 - acc: 0.4920 - val_loss: 1.2967 - val_acc: 0.4693
Epoch 21/30
85/86 [============================>.] - ETA: 0s - loss: 1.1095 - acc: 0.4757

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 34ms/step - loss: 1.1080 - acc: 0.4766 - val_loss: 1.2449 - val_acc: 0.4803
Epoch 22/30
86/86 [==============================] - 2s 22ms/step - loss: 1.1130 - acc: 0.4693 - val_loss: 1.3355 - val_acc: 0.4781
Epoch 23/30
85/86 [============================>.] - ETA: 0s - loss: 1.1349 - acc: 0.4654

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 35ms/step - loss: 1.1314 - acc: 0.4671 - val_loss: 1.2412 - val_acc: 0.4759
Epoch 24/30
85/86 [============================>.] - ETA: 0s - loss: 1.0689 - acc: 0.4809

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 39ms/step - loss: 1.0674 - acc: 0.4817 - val_loss: 1.2194 - val_acc: 0.5000
Epoch 25/30
86/86 [==============================] - 2s 23ms/step - loss: 1.1042 - acc: 0.4846 - val_loss: 1.2267 - val_acc: 0.5088
Epoch 26/30
86/86 [==============================] - 2s 22ms/step - loss: 1.0974 - acc: 0.4788 - val_loss: 1.2357 - val_acc: 0.4561
Epoch 27/30
86/86 [==============================] - 2s 21ms/step - loss: 1.1058 - acc: 0.5022 - val_loss: 1.2784 - val_acc: 0.3355
Epoch 28/30
86/86 [==============================] - 2s 22ms/step - loss: 1.1123 - acc: 0.4700 - val_loss: 1.2350 - val_acc: 0.5329
Epoch 29/30
85/86 [============================>.] - ETA: 0s - loss: 1.1091 - acc: 0.4838

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_of.tf/assets


86/86 [==============================] - 3s 35ms/step - loss: 1.1103 - acc: 0.4832 - val_loss: 1.1901 - val_acc: 0.5044
Epoch 30/30
86/86 [==============================] - 2s 21ms/step - loss: 1.1421 - acc: 0.4846 - val_loss: 1.1971 - val_acc: 0.5329


In [19]:
model = tf.keras.models.load_model('./res/V_model_CNNLSTMAtt_of.tf/')
pred = model.predict(np.asarray(visual_of['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 6ms/step
              precision    recall  f1-score   support

         Neg     0.5351    0.9516    0.6851       248
         Pos     0.1333    0.0143    0.0258       140
         Neu     0.0000    0.0000    0.0000        69

    accuracy                         0.5208       457
   macro avg     0.2228    0.3220    0.2370       457
weighted avg     0.3313    0.5208    0.3797       457

[[236  12   0]
 [137   2   1]
 [ 68   1   0]]


In [20]:
x = Input((10, 512))
h = Attention_Self(512)(x)
h = Conv1D(64, 3, 1, 'same')(h)
h = Conv1D(64, 1, 1, 'same')(h)
h = Conv1D(64, 3, 1, 'same')(h)
h = LSTM(64, activation='relu')(h)
res = Dense(3, 'softmax')(h)

model = Model(inputs=x, outputs=res)
model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics='acc')
model.summary()

Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_7 (InputLayer)        [(None, 10, 512)]         0         
                                                                 
 attention__self_5 (Attentio  (None, 10, 512)          525825    
 n_Self)                                                         
                                                                 
 conv1d_15 (Conv1D)          (None, 10, 64)            98368     
                                                                 
 conv1d_16 (Conv1D)          (None, 10, 64)            4160      
                                                                 
 conv1d_17 (Conv1D)          (None, 10, 64)            12352     
                                                                 
 lstm_7 (LSTM)               (None, 64)                33024     
                                                           

In [21]:
callback_list = [ModelCheckpoint(filepath='./res/V_model_CNNLSTMAtt_clip.tf', monitor='val_loss', save_best_only=True, save_freq='epoch')]

model.fit(x=np.asarray(visual_clip['train']), y=np.asarray(label['train']), batch_size=16, epochs=30, 
            validation_data=[np.asarray(visual_clip['valid']), np.asarray(label['valid'])],
            callbacks=callback_list)

Epoch 1/30
82/86 [===========================>..] - ETA: 0s - loss: 1.0669 - acc: 0.5061

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_clip.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_clip.tf/assets


86/86 [==============================] - 4s 34ms/step - loss: 1.0632 - acc: 0.5073 - val_loss: 0.9842 - val_acc: 0.5439
Epoch 2/30
86/86 [==============================] - 1s 17ms/step - loss: 0.9838 - acc: 0.5461 - val_loss: 0.9999 - val_acc: 0.5461
Epoch 3/30
86/86 [==============================] - 1s 13ms/step - loss: 0.9669 - acc: 0.5490 - val_loss: 0.9955 - val_acc: 0.5570
Epoch 4/30
86/86 [==============================] - 1s 12ms/step - loss: 0.9248 - acc: 0.5870 - val_loss: 1.0004 - val_acc: 0.5241
Epoch 5/30
86/86 [==============================] - 1s 12ms/step - loss: 0.8859 - acc: 0.6148 - val_loss: 1.0277 - val_acc: 0.5373
Epoch 6/30
86/86 [==============================] - 1s 13ms/step - loss: 0.8749 - acc: 0.6250 - val_loss: 1.0532 - val_acc: 0.5680
Epoch 7/30
85/86 [============================>.] - ETA: 0s - loss: 0.9104 - acc: 0.6221

INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_clip.tf/assets


INFO:tensorflow:Assets written to: ./res/V_model_CNNLSTMAtt_clip.tf/assets


86/86 [==============================] - 2s 26ms/step - loss: 0.9113 - acc: 0.6221 - val_loss: 0.9741 - val_acc: 0.5504
Epoch 8/30
86/86 [==============================] - 1s 12ms/step - loss: 1.0167 - acc: 0.5000 - val_loss: 0.9939 - val_acc: 0.5570
Epoch 9/30
86/86 [==============================] - 1s 12ms/step - loss: 0.9650 - acc: 0.5680 - val_loss: 1.6236 - val_acc: 0.5439
Epoch 10/30
86/86 [==============================] - 1s 12ms/step - loss: 0.9108 - acc: 0.5980 - val_loss: 1.0181 - val_acc: 0.5504
Epoch 11/30
86/86 [==============================] - 1s 12ms/step - loss: 0.8157 - acc: 0.6696 - val_loss: 1.2824 - val_acc: 0.4978
Epoch 12/30
86/86 [==============================] - 1s 16ms/step - loss: 0.9338 - acc: 0.5702 - val_loss: 1.0673 - val_acc: 0.5439
Epoch 13/30
86/86 [==============================] - 2s 18ms/step - loss: 1.0534 - acc: 0.5424 - val_loss: 1.0393 - val_acc: 0.5439
Epoch 14/30
86/86 [==============================] - 1s 16ms/step - loss: 1.0299 - acc: 0.

In [22]:
model = tf.keras.models.load_model('./res/V_model_CNNLSTMAtt_clip.tf/')
pred = model.predict(np.asarray(visual_clip['test']))
predicted_test_labels = pred.argmax(axis=1)
numeric_test_labels = np.array(label['test'])
            
eval_res = classification_report(numeric_test_labels, predicted_test_labels, 
                                    target_names = ['Neg', 'Pos', 'Neu'], 
                                    digits=4, output_dict=False)

print(eval_res)

cm = confusion_matrix(y_true=numeric_test_labels.tolist(), y_pred=predicted_test_labels.tolist())
print(cm)

15/15 [==============================] - 0s 3ms/step
              precision    recall  f1-score   support

         Neg     0.5427    1.0000    0.7035       248
         Pos     0.0000    0.0000    0.0000       140
         Neu     0.0000    0.0000    0.0000        69

    accuracy                         0.5427       457
   macro avg     0.1809    0.3333    0.2345       457
weighted avg     0.2945    0.5427    0.3818       457

[[248   0   0]
 [140   0   0]
 [ 69   0   0]]


/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/chason/anaconda3/envs/deepeye/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le